--EXERCICIO 2
ALTER TABLE CLIENTE DROP 
    CONSTRAINT CLIENTEPK
ALTER TABLE ATOR DROP
    CONSTRAINT ATORPK
ALTER TABLE CLASSIFICACAO DROP 
    CONSTRAINT CLASSIFICACAOPK
ALTER TABLE FILME DROP
    CONSTRAINT FILMEPF
ALTER TABLE FILME DROP
    CONSTRAINT FILMEFK
ALTER TABLE MIDIA DROP
    CONSTRAINT MIDIAPK
ALTER TABLE MIDIA DROP
    CONSTRAINT MIDIAFK
ALTER TABLE ESTRELA DROP
    CONSTRAINT ESTRELAPK
ALTER TABLE ESTRELA DROP
    CONSTRAINT ESTRELAFK
ALTER TABLE EMPRESTIMO DROP
    CONSTRAINT EMPRESTIMOPK
ALTER TABLE EMPRESTIMO DROP
    CONSTRAINT EMPRESTIMOFK