
CREATE TABLE CLIENTE (
   CODCLI INTEGER NOT NULL,
   NOMECLI VARCHAR(50) NOT NULL,
   ENDERECO VARCHAR(60),
   CIDADE CHAR (20) NOT NULL,
   CEP CHAR(10),
   UF CHAR (2) NOT NULL, 
   CGC CHAR(14) NOT NULL,
   PRIMARY KEY (CODCLI)
);

CREATE TABLE VENDEDOR (
   CODVEND INTEGER NOT NULL,
   NOMEVEND VARCHAR(50) NOT NULL,
   SALFIXO FLOAT,
   FAIXACOMIS CHAR NOT NULL,
   PRIMARY KEY (CODVEND)
);

CREATE TABLE PRODUTO (
   CODPROD INTEGER NOT NULL,
   UNIDADE CHAR(2) NOT NULL,
   DESCRI VARCHAR(30) NOT NULL,
   VALUNIT FLOAT,
   PRIMARY KEY (CODPROD)
);

CREATE TABLE PEDIDO (
   NUMPED INTEGER NOT NULL,
   PRAZOENTR INTEGER,
   CODCLI INTEGER NOT NULL,
   CODVEND INTEGER,
   PRIMARY KEY (NUMPED),
   FOREIGN KEY (CODCLI) REFERENCES CLIENTE (CODCLI),
   FOREIGN KEY (CODVEND) REFERENCES VENDEDOR (CODVEND)
);

CREATE TABLE ITEMPED (
   NUMPED INTEGER NOT NULL,
   CODPROD INTEGER NOT NULL,
   QUANT INTEGER,
   PRIMARY KEY (NUMPED, CODPROD),
   FOREIGN KEY (NUMPED) REFERENCES PEDIDO (NUMPED),
   FOREIGN KEY (CODPROD) REFERENCES PRODUTO (CODPROD)
);